# Generated by Django 5.1.4 on 2025-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('date', models.DateField(verbose_name='Дата окончания')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
            ],
        ),
    ]
