# Generated by Django 5.1.4 on 2025-01-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_question_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Группа вопросов')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='?', max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.question_block'),
        ),
    ]
