# Generated by Django 5.1.4 on 2025-01-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_question_block_alter_question_title_question_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_block',
            options={'ordering': ['title']},
        ),
    ]
