# Generated by Django 5.1.4 on 2025-02-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_question_block_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.question_block'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
