# Generated by Django 5.1.4 on 2025-02-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_task_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['importance', 'date']},
        ),
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.question_block'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('о', 'Очень'), ('с', 'Средне'), ('ф', 'Фигня')], default='ф', max_length=1, verbose_name='Важность'),
        ),
    ]
