# Generated by Django 5.1.4 on 2025-02-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_task_options_alter_question_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.question_block'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('в', 'Высокая'), ('н', 'Норм')], default='н', max_length=1, verbose_name='Важность'),
        ),
    ]
