# Generated by Django 5.1.4 on 2025-02-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_question_block_alter_task_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блок задач')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['importance', 'title']},
        ),
        migrations.AddField(
            model_name='task',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.task_block'),
        ),
    ]
