# Generated by Django 5.1.4 on 2025-02-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_task_block_alter_task_options_task_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['block', 'importance', 'title']},
        ),
    ]
