# Generated by Django 5.1.4 on 2025-02-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.task_block', verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Question_block',
        ),
    ]
