# Generated by Django 5.1.4 on 2025-02-17 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_task_block_title_alter_task_block_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_block',
            new_name='TaskBlock',
        ),
    ]
