# Generated by Django 5.2.1 on 2025-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_completed_alter_task_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="importance",
            field=models.BooleanField(default=False, verbose_name="Важность"),
        ),
    ]
