# Generated by Django 5.2.1 on 2025-06-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_importance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Блок задач")),
            ],
            options={
                "verbose_name": "Блок задач",
                "verbose_name_plural": "Блоки задач",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["title"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.taskblock",
                verbose_name="Блок задач",
            ),
        ),
    ]
