# Generated by Django 5.2.1 on 2025-06-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_taskblock_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="block",
            new_name="taskblock",
        ),
    ]
