# Generated by Django 5.2.1 on 2025-06-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_rename_block_task_taskblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archive",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
    ]
