# Generated by Django 5.2.1 on 2025-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок"),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Сделано"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Задача"),
        ),
    ]
