# Generated by Django 5.2.1 on 2025-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_remove_task_date_task_deadline_alter_task_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archive_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата помещения в архив"
            ),
        ),
    ]
